export const weekMessages = {
  1: "Conception begins—your body changes are subtle, but an embryo is forming.",
  2: "Implantation happens—hormones shift even before you miss a period.",
  3: "Cells are multiplying—this is early organ formation.",
  4: "Your little embryo is developing rapidly—most people don’t know they’re pregnant yet.",
  5: "Neural tube and heart begin forming—take care with folate!",
  6: "Heartbeat starts—morning sickness often begins.",
  7: "Bones and eyelids are forming—time to schedule your first antenatal visit.",
  8: "Major organs are developing—placenta is working hard.",
  9: "Baby is now around half an inch—teeth buds start forming.",
  10: "Digits and nails are appearing—heart sounds may be audible.",
  11: "Bones harden—first trimester nears end.",
  12: "Baby about the size of a plum—organs formed.",
  13: "Second trimester begins—energy often returns.",
  14: "Facial features refining—more energy.",
  15: "Baby may respond to sounds—baby’s kidneys produce urine.",
  16: "Movements may start—baby’s eyelids and ears form.",
  17: "Baby adds fat—consider antenatal classes.",
  18: "You may find out baby’s gender—feel light-headed sometimes.",
  19: "Belly shows—baby can hear noises.",
  20: "Mid-pregnancy ultrasound—baby very active.",
  21: "Consider travel plans—pregnancy restrictions may apply.",
  22: "Braxton Hicks contractions may begin.",
  23: "Baby practicing breathing—expect incontinence.",
  24: "Baby grows rapidly—movement gets stronger.",
  25: "Discomfort as baby grows—start stretching.",
  26: "Baby adds fat; your gravity shifts.",
  27: "Third trimester begins—stretch marks and weight gain common.",
  28: "Third trimester fully underway—common discomforts like heartburn start.",
  29: "Baby weighs about 1 kg—shortness of breath may increase.",
  30: "Baby’s reflexes develop—you may feel sore and tired.",
  31: "Tiredness and emotional changes—take time for self-care.",
  32: "Baby still moves a lot—expect back/pelvic pain.",
  33: "Nervous system develops—more weight gain.",
  34: "Vernix (wax) protects baby’s skin; baby drops.",
  35: "Braxton Hicks increase—birth prep intensifies.",
  36: "Baby crowded in womb—kick monitoring important.",
  37: "Full-term begins—get plenty of rest.",
  38: "Baby ready—ensure hospital bag is packed.",
  39: "Early labor signs may appear—stay ready.",
  40: "Congratulations—you’ve reached your due date!",
};
